#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          Spinner,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Flag,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Wrist,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	getJoystickSettings(joystick);
	waitForStart();
	motor[Lift] = 100;
	wait1Msec(750);
	motor[Lift] = 0;
	motor[Left] = 100;
	motor[Right] = 100;
	wait1Msec(1050);
	motor[Left] = 100;
	motor[Right] = -100;
	wait1Msec(500);
	motor[Left] = 100;
	motor[Right] = 100;
	wait1Msec(1050);
	motor[Left] = 0;
	motor[Right] = 0;
}
