#pragma config(Sensor, S1,     HTAC,           sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-accelerometer.h"

bool go = true;
int _x_axis = 0;
int _y_axis = 0;
int _z_axis = 0;

string _tmp;

task main()
{
	while(go)
	{
		eraseDisplay();
		if (!HTACreadAllAxes(HTAC , _x_axis, _y_axis, _z_axis))
		{
			nxtDisplayTextLine(4, "ERROR!!");
			wait1Msec(2000);
			StopAllTasks();
		}
		nxtDisplayTextLine(2, "   X    Y    Z");
		StringFormat(_tmp, "%4d %4d", _x_axis, _y_axis);
		nxtDisplayTextLine(3, "%s %4d", _tmp, _z_axis);
		wait1Msec(100);
	}
}
