#pragma config(Sensor, S1,     accel,           sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-accelerometer.h"

int pitch = 0; // x-axis
int bank = 0; // y-axis
int z = 0; // z-axis

string _tmp;

task main()
{
	while(true)
	{
		eraseDisplay();
		HTACreadAllAxes(accel, pitch, bank, z);
		nxtDisplayTextLine(2, "   X    Y    Z");
		StringFormat(_tmp, "%4d %4d", pitch, bank);
		nxtDisplayTextLine(3, "%s %4d", _tmp, z);
		wait1Msec(100);
	}
}
