#pragma config(Sensor, S1,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     Acc,            sensorI2CHiTechnicAccel)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     Touch,          sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-gyro.h"
#include "drivers/hitechnic-irseeker-v2.h"

#define irpower 40

bool irseek = true;
int irval;
task main()
{
	eraseDisplay();
	while(irseek)
	{
		irval = SensorValue[IR];
		if(irval != 5)
		{
			nxtDisplayString( 1, "%d", irval);
			//motor[leftDrive] = irpower;
			//motor[rightDrive] = irpower;
		}
		else
		{
			nxtDisplayString( 1, "%d", irval);
			//motor[leftDrive] = 0;
			//motor[rightDrive] = 0;
			//irseek = false;
		}
		//nxtDisplayString( 1, "%d", IRValue);
	}
}
