#pragma config(Sensor, S3,     eopd,           sensorAnalogActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-eopd.h"

int processedDist;

task main()
{
	HTEOPDsetLongRange(eopd);
	while(true)
	{
		eraseDisplay();
		processedDist = HTEOPDreadProcessed(eopd);
		nxtDisplayTextLine(1 ,"%2d", processedDist);
		wait1Msec(50);
	}
}
