#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "drivers/hitechnic-irseeker-v2.h"
//#include "JoystickDriver.c"

int irval;
bool irseek = true;

task main()
{
	eraseDisplay();
	while (irseek)
	{
		irval = SensorValue[IR];
		nxtDisplayString( 1, "%d", irval);
	}
}
