#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    A1,                   tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    B1,                   tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	int a = 110;
	int buffer = 15;
	while(true)
	{
		getJoystickSettings(joystick);
		eraseDisplay();
		if (joystick.joy1_y2 < -buffer)
		{
			a=a-2;
			nxtDisplayString( 1, "%d", a);
			servo[A1] = a; // full forward
			wait1Msec(50);
			if (a >= 255)
			{
				a = 255;
				servo[A1] = a;
				PlaySound(soundBeepBeep);
				wait1Msec(500);
			}
		}
		else if (joystick.joy1_y2 > buffer)
		{
			a = a+2;
			nxtDisplayString( 1, "%d", a);
			servo[A1] = a; // full back
			wait1Msec(50);
			if (a <= 10)
			{
				a = 10;
				servo[A1] = a;
				PlaySound(soundBeepBeep);
				wait1Msec(500);
			}
		}
		else
		{
			if (a <= 10)
			{
				a = 10;
				servo[A1] = a;
				PlaySound(soundBeepBeep);
				wait1Msec(500);
			}
			else if (a >= 255)
			{
				a = 255;
				servo[A1] = a;
				PlaySound(soundBeepBeep);
				wait1Msec(500);
			}
			nxtDisplayString( 1, "%d", a);
			wait1Msec(50);
		}
	}
	/*if (joy1Btn(5)) // FWD
	{
	servo[A1] = 255;
	servo[A2] = 255; ///////*
	servo[B1] = 255;
	servo[B2] = 255;
	}
	else if (joy1Btn(6)) // BKD
	{
	servo[A1] = 0;
	servo[A2] = 0;
	servo[B1] = 0;
	servo[B2] = 0;
	}
	else								// Stop
	{
	servo[A1] = 128;
	servo[A2] = 128;
	servo[B1] = 128;
	servo[B2] = 128;
	}*/
}
