#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    A1,                   tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_2,    B1,                   tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_3,    A2,                   tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_4,    B2,                   tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if (joy1Btn(5)) // FWD
		{
			servo[A1] = 255;
			servo[A2] = 255;
			servo[B1] = 255;
			servo[B2] = 255;
		}
		else if (joy1Btn(6)) // BKD
		{
			servo[A1] = 0;
			servo[A2] = 0;
			servo[B1] = 0;
			servo[B2] = 0;
		}
		else								// Stop
		{
			servo[A1] = 128;
			servo[A2] = 128;
			servo[B1] = 128;
			servo[B2] = 128;
		}
	}
}
